%% initial trial to try different plotting options but nothing implemented

myTtile='Auto correlated locators'' variation'; % two consequtive apostrophe for printing one apostrophe

h=figure('Units','centimeters');%210 × 297 millimeters 
h.Position=[5,10,15,10];
h.PaperPositionMode='auto';
ncLine=plot(devNc,'Marker','o');
hold all; 
clampLine=plot(devClamps,'Marker','+');
myAxis=h.CurrentAxes;                                        % queries the axis from the axis
% allLines=[ncLine;clampLine];
% cmap2 = cbrewer('qual','Set1',length(allLines));

cmapNC = cbrewer('seq','Reds',2*length(ncLine));
cmapNC=flipud(cmapNC);
% cmapNC = cbrewer('seq','Greys',length(clampLine));
cmapClamp = cbrewer('seq','Blues',2*length(clampLine));
cmapClamp=flipud(cmapClamp);

legNcCell=cell(length(ncLine),1);
for i=1:length(ncLine)
   ncLine(i).LineWidth=1.5;
   ncLine(i).Color=cmapNC(i,:); 
   ncLine(i).MarkerFaceColor=cmapNC(i,:); 
   ncLine(i).MarkerEdgeColor='none';
   legNcCell{i}=sprintf('%i',i);
end

legClampCell=cell(length(clampLine),1);
for i=1:length(clampLine)
   clampLine(i).LineWidth=1.5;
   clampLine(i).Color=cmapClamp(i,:); 
   clampLine(i).MarkerFaceColor=cmapClamp(i,:);
   legClampCell{i}=sprintf('%i',i);
%    clampLine(i).MarkerEdgeColor='none';
end



hTitle  = title (myTtile);       
hXLabel =xlabel('n^{th} time instance');
hYLabel =ylabel('Deviation in mm');


set( myAxis                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(myAxis, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , -100:1:100, ...
  'LineWidth'   , 1         );

[hl(2).leg, hl(2).obj, hl(2).hout, hl(2).mout] = ...
legendflex(ncLine, legNcCell, ...
'anchor', {'ne','ne'}, ...
'buffer', [-5 -5], ...
'nrow',   1,...
'fontsize',10, ...
'xscale', 0.66, ...
'box','off',...
'title', 'NC Blocks');

[hl(3).leg, hl(3).obj, hl(3).hout, hl(3).mout] = ...
legendflex(clampLine, legClampCell, ...
'ref', hl(2).leg, ...
'anchor', {'se','ne'}, ...
'buffer', [0 0], ...
'nrow',   1,...
'fontsize', 10', ...
'box','off',...
'title', 'Clamps');


print(h,myTtile,'-dpng')

